// Generated by CoffeeScript 1.6.3
(function() {
  'use strict';
  var AngularBase, install_angular_cls;

  window.ciboulot = {};

  AngularBase = (function() {
    function AngularBase() {}

    AngularBase.prototype.__name = 'AngularBase';

    AngularBase.prototype.__injections = ['$log'];

    AngularBase.prototype.__inject = function(cls, injected_values) {
      /*
      inject value directly into the prototype
      */

      var i, injection, value, _i, _len, _results;
      _results = [];
      for (i = _i = 0, _len = injected_values.length; _i < _len; i = ++_i) {
        value = injected_values[i];
        injection = cls.prototype.__injections[i];
        _results.push(cls.prototype[injection] = value);
      }
      return _results;
    };

    AngularBase.prototype.__factory = function(cls) {
      return cls;
    };

    AngularBase.prototype.__module_install_function = function(cls, module) {
      return function() {
        return console.log('NOT IMPLEMENTED');
      };
    };

    AngularBase.prototype.__install = function(cls, module) {
      var factory, injections_and_factory, module_install_function, name;
      factory = function() {
        cls.prototype.__inject(cls, arguments);
        return cls.prototype.__factory(cls);
      };
      name = cls.prototype.__name;
      injections_and_factory = cls.prototype.__injections.concat(factory);
      module_install_function = cls.prototype.__module_install_function(cls, module);
      return module_install_function(name, injections_and_factory);
    };

    return AngularBase;

  })();

  install_angular_cls = function(module, cls) {
    return cls.prototype.__install(cls, module);
  };

  window.ciboulot[AngularBase.prototype.__name] = AngularBase;

  window.ciboulot['install_angular_cls'] = install_angular_cls;

}).call(this);
